# -*- coding: utf-8 -*-
"""Untitled9.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gCqSwYRSE9cfQLd09pqJgiT3bWSrAiDa
"""

import streamlit as st
import joblib

# Load the pre-trained model
model = joblib.load('model.pkl')

st.title("Model Deployment as Data Product")

# Allow users to input features dynamically
st.write("Enter feature values (comma-separated):")
user_input = st.text_input("Features")

# Predict on submit
if st.button("Predict"):
    try:
        # Convert user input to a list of floats
        features = list(map(float, user_input.split(',')))

        # Predict using the model
        prediction = model.predict([features])

        # Display prediction
        st.success(f"Prediction: {prediction[0]}")
    except ValueError:
        st.error("Invalid input. Please enter numerical values separated by commas.")
    except Exception as e:
        st.error(f"Error: {str(e)}")